name: node.js deploy

on:
  push:
    branches:
      - main
  watch:
    types: [started]

jobs:
  run_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v1
      - name: Run node.js and push files to repo
        uses: C4illin/node.js-run-and-push@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          JSFILE: "getAllURLs.js"
          BRANCH: "main"
